# Generated by Django 5.2 on 2025-04-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uusername',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
