# Generated by Django 5.2 on 2025-04-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_profile_uusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/media/avatars/default-avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
