# Generated by Django 5.2 on 2025-04-16 18:29

from django.db import migrations

def fill_uusername(apps, schema_editor):
    Profile = apps.get_model('social', 'Profile')
    for profile in Profile.objects.all():
        if profile.user:
            profile.uusername = profile.user.username.lower()
            profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_profile_avatar'),
    ]

    operations = [
        migrations.RunPython(fill_uusername),
    ]
