# Generated by Django 5.2 on 2025-04-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_auto_20250416_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uusername',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
