# Generated by Django 5.2 on 2025-04-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_alter_profile_uusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text_com',
            field=models.TextField(),
        ),
    ]
