# Generated by Django 5.2 on 2025-04-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
