# Generated by Django 5.2 on 2025-04-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_complaint_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='accepted',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
