# Generated by Django 5.2 on 2025-05-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0016_alter_complaint_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="uusername",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
