# Generated by Django 5.2 on 2025-05-22 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0017_alter_profile_uusername"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="saved",
            field=models.ManyToManyField(
                blank=True,
                related_name="saved_publications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
